package org.os4all.modules.digitaltwin.fhir.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.os4all.modules.digitaltwin.entity.HistoricalMedicalRecord;
import org.os4all.modules.digitaltwin.fhir.dto.FhirParsedPatient;
import org.os4all.modules.digitaltwin.fhir.mapper.FhirPatientMapper;
import org.os4all.modules.digitaltwin.repository.HistoricalMedicalRecordRepository;
import org.os4all.modules.digitaltwin.service.DigitalTwinSimulationEngine;
import org.os4all.modules.lab.entity.LabResult;
import org.os4all.modules.lab.repository.LabResultRepository;
import org.os4all.modules.normalization.UnitNormalizationService;
import org.os4all.modules.user.entity.Role;
import org.os4all.modules.user.entity.User;
import org.os4all.modules.user.entity.UserProfile;
import org.os4all.modules.user.repository.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.File;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.time.LocalDate;
import java.util.*;

/**
 * Service that scans, parses, and ingests synthetic FHIR bundles generated by Synthea
 * into the OS4All Digital Twin static EHR repositories.
 */
@Service
public class FhirImportService {

    private static final Logger log = LoggerFactory.getLogger(FhirImportService.class);

    private final String defaultFhirPath;
    private final ObjectMapper objectMapper;
    private final FhirPatientMapper patientMapper;
    private final UserRepository userRepository;
    private final HistoricalMedicalRecordRepository medicalRecordRepository;
    private final LabResultRepository labResultRepository;
    private final UnitNormalizationService normService;
    private final PasswordEncoder passwordEncoder;
    private final DigitalTwinSimulationEngine simulationEngine;

    public FhirImportService(
            @Value("${app.synthea.fhir-path:D:/Projects/synthea-master/output/fhir}") String defaultFhirPath,
            ObjectMapper objectMapper,
            FhirPatientMapper patientMapper,
            UserRepository userRepository,
            HistoricalMedicalRecordRepository medicalRecordRepository,
            LabResultRepository labResultRepository,
            UnitNormalizationService normService,
            PasswordEncoder passwordEncoder,
            DigitalTwinSimulationEngine simulationEngine
    ) {
        this.defaultFhirPath = defaultFhirPath;
        this.objectMapper = objectMapper;
        this.patientMapper = patientMapper;
        this.userRepository = userRepository;
        this.medicalRecordRepository = medicalRecordRepository;
        this.labResultRepository = labResultRepository;
        this.normService = normService;
        this.passwordEncoder = passwordEncoder;
        this.simulationEngine = simulationEngine;
    }

    public record ImportSummary(
            int totalBundlesScanned,
            int candidatePatientsFound,
            int patientsImported,
            List<String> importedPatientNames,
            String sourcePath,
            String statusMessage
    ) {}

    /**
     * Inspects FHIR directory and parses all patient candidate bundles without mutating the DB.
     */
    public List<FhirParsedPatient> scanCandidatePatients(String customPath) {
        String dirPath = resolveSafePath(customPath);
        File dir = new File(dirPath);
        if (!dir.exists() || !dir.isDirectory()) {
            log.warn("Synthea FHIR directory does not exist or is not a directory: {}", dirPath);
            return List.of();
        }

        File[] jsonFiles = dir.listFiles((d, name) -> name.endsWith(".json") && !name.contains("Information"));
        if (jsonFiles == null || jsonFiles.length == 0) {
            return List.of();
        }

        List<FhirParsedPatient> candidates = new ArrayList<>();
        for (File f : jsonFiles) {
            try {
                JsonNode root = objectMapper.readTree(f);
                FhirParsedPatient parsed = patientMapper.mapPatientBundle(root, f.getName());
                if (parsed != null) {
                    candidates.add(parsed);
                }
            } catch (Exception e) {
                log.warn("Failed to parse FHIR file {}: {}", f.getName(), e.getMessage());
            }
        }

        return candidates;
    }

    /**
     * Imports curated diabetes/metabolic patients from Synthea into OS4All Static EHR tables.
     */
    @Transactional
    public ImportSummary importSyntheaCohort(String customPath, boolean metabolicOnly) {
        String dirPath = resolveSafePath(customPath);
        List<FhirParsedPatient> candidates = scanCandidatePatients(dirPath);
        if (candidates.isEmpty()) {
            return new ImportSummary(0, 0, 0, List.of(), dirPath, "No Synthea FHIR bundles found at path.");
        }

        List<FhirParsedPatient> selected = candidates.stream()
                .filter(p -> !metabolicOnly || p.hasType2Diabetes() || p.hasPrediabetes() || !p.labs().isEmpty())
                .sorted(Comparator.comparing((FhirParsedPatient p) -> p.fullName().contains("Senger") || p.fullName().contains("Shara")).reversed()
                        .thenComparing(FhirParsedPatient::hasType2Diabetes).reversed()
                        .thenComparing(FhirParsedPatient::hasPrediabetes).reversed())
                .limit(10) // Curated cohort of top metabolic profiles including primary demo patient
                .toList();

        List<String> importedNames = new ArrayList<>();
        for (FhirParsedPatient p : selected) {
            persistPatientEhr(p);
            importedNames.add(p.fullName() + " (" + (p.hasType2Diabetes() ? "T2D" : (p.hasPrediabetes() ? "Prediabetes" : "Metabolic")) + ")");
        }

        return new ImportSummary(
                candidates.size(),
                selected.size(),
                selected.size(),
                importedNames,
                dirPath,
                String.format("Successfully ingested %d curated synthetic patients from Synthea FHIR.", selected.size())
        );
    }

    private void persistPatientEhr(FhirParsedPatient p) {
        User user = userRepository.findByEmail(p.email())
                .or(() -> userRepository.findById(p.id()))
                .orElseGet(() -> {
                    User u = new User();
                    u.setId(p.id());
                    u.setEmail(p.email());
                    u.setFullName(p.fullName() + " [Synthea FHIR]");
                    u.setPasswordHash(passwordEncoder.encode("SyntheaSyntheticPass2026!"));
                    u.setRole(Role.ROLE_USER);
                    u.setActive(true);

                    UserProfile profile = new UserProfile();
                    profile.setUser(u);
                    profile.setDateOfBirth(p.birthDate());
                    profile.setBiologicalSex(p.gender());
                    profile.setHeightCm(p.heightCm() != null ? p.heightCm() : new BigDecimal("170.0"));
                    profile.setWeightKg(p.weightKg() != null ? p.weightKg() : new BigDecimal("75.0"));
                    profile.setBloodType("O+");

                    StringBuilder lifestyle = new StringBuilder();
                    lifestyle.append("Imported from Synthea FHIR bundle: ").append(p.sourceFile()).append(". ");
                    if (p.hasType2Diabetes()) lifestyle.append("Established clinical Type 2 Diabetes history. ");
                    if (p.hasPrediabetes()) lifestyle.append("Documented prediabetes glycemic history. ");
                    if (p.hasHypertension()) lifestyle.append("Hypertensive cardiovascular history. ");
                    if (p.bloodPressureSystolic() != null) {
                        lifestyle.append(String.format("Historical BP: %s/%s mmHg. ", p.bloodPressureSystolic(), p.bloodPressureDiastolic()));
                    }
                    profile.setLifestyleNotes(lifestyle.toString().trim());

                    u.setProfile(profile);
                    return userRepository.save(u);
                });

        // 2. Persist Conditions
        if (medicalRecordRepository.countByUserId(user.getId()) == 0) {
            Set<String> seenConditions = new HashSet<>();
            for (FhirParsedPatient.FhirParsedCondition c : p.conditions()) {
                if (c.name() == null || c.name().isBlank()) continue;
                String lower = c.name().trim().toLowerCase();
                if (seenConditions.add(lower)) {
                    HistoricalMedicalRecord rec = new HistoricalMedicalRecord();
                    rec.setId(UUID.randomUUID());
                    rec.setUser(user);
                    rec.setRecordType("CONDITION");
                    rec.setConditionOrDiagnosis(c.name());
                    rec.setIcd10Code(c.code());
                    rec.setStatus("ACTIVE");
                    rec.setDiagnosedDate(c.onsetDate() != null ? c.onsetDate() : LocalDate.of(2015, 1, 1));
                    if (!p.medications().isEmpty()) {
                        rec.setMedications(String.join(", ", p.medications()));
                    }
                    rec.setClinicalNotes("Synthea longitudinal clinical finding.");
                    medicalRecordRepository.save(rec);
                }
            }
        }

        // 3. Persist Key Metabolic Lab Biomarkers (HbA1c, Glucose, Lipids, Creatinine)
        if (labResultRepository.countByUserId(user.getId()) == 0) {
            int labCount = 0;
            for (FhirParsedPatient.FhirParsedLab l : p.labs()) {
                String bName = l.name().toLowerCase();
                if (bName.contains("hemoglobin a1c") || bName.contains("glucose") || bName.contains("cholesterol")
                        || bName.contains("creatinine") || bName.contains("urea") || bName.contains("triglyceride")
                        || bName.contains("microalbumin")) {

                    String rawBio = l.name() != null ? l.name().trim() : "Biomarker";
                    if (rawBio.length() > 95) rawBio = rawBio.substring(0, 95);

                    String stdBio = cleanBiomarkerName(l.name());
                    if (stdBio.length() > 95) stdBio = stdBio.substring(0, 95);

                    Instant collDate = parseInstantSafe(l.dateIso());

                    LabResult lab = new LabResult();
                    lab.setId(UUID.randomUUID());
                    lab.setUser(user);
                    lab.setBiomarker(rawBio);
                    lab.setStandardizedBiomarker(stdBio);
                    lab.setValue(l.value());
                    lab.setUnit(l.unit() != null && l.unit().length() > 45 ? l.unit().substring(0, 45) : l.unit());
                    lab.setStandardValue(l.value());
                    lab.setStandardUnit(lab.getUnit());
                    lab.setCollectionDate(collDate);
                    lab.setSourceReport("Synthea FHIR: " + p.sourceFile());
                    lab.setConfidence(BigDecimal.valueOf(1.00));
                    lab.setIsConfirmed(true);
                    labResultRepository.save(lab);

                    labCount++;
                    if (labCount >= 20) break;
                }
            }
        }

        // 4. Seed initial longitudinal wearable baseline & Digital Twin state
        try {
            if (p.hasType2Diabetes()) {
                simulationEngine.injectScenario(user.getId(), "GLUCOSE_SPIKE");
            } else if (p.hasPrediabetes()) {
                simulationEngine.injectScenario(user.getId(), "POOR_SLEEP");
            } else {
                simulationEngine.injectScenario(user.getId(), "STABLE_PATIENT");
            }
        } catch (Exception e) {
            log.warn("Could not inject default simulation scenario for Synthea patient {}: {}", user.getId(), e.getMessage());
        }
    }

    private Instant parseInstantSafe(String dateIso) {
        if (dateIso == null || dateIso.isBlank()) return Instant.now();
        try {
            if (dateIso.length() == 10) return LocalDate.parse(dateIso).atStartOfDay(java.time.ZoneOffset.UTC).toInstant();
            return Instant.parse(dateIso);
        } catch (Exception ignored) {
            return Instant.now();
        }
    }

    private String cleanBiomarkerName(String raw) {
        String lower = raw.toLowerCase();
        if (lower.contains("hemoglobin a1c")) return "HbA1c";
        if (lower.contains("glucose")) return "Fasting Blood Glucose";
        if (lower.contains("ldl")) return "LDL Cholesterol";
        if (lower.contains("hdl")) return "HDL Cholesterol";
        if (lower.contains("triglyceride")) return "Triglycerides";
        if (lower.contains("cholesterol")) return "Total Cholesterol";
        if (lower.contains("creatinine")) return "Serum Creatinine";
        if (lower.contains("urea")) return "Blood Urea Nitrogen";
        return raw.split("\\[")[0].trim();
    }

    private String resolveSafePath(String customPath) {
        if (customPath != null && !customPath.isBlank()) {
            // Prevent arbitrary directory traversal attacks
            String sanitized = customPath.replace("..", "").trim();
            File f = new File(sanitized);
            if (f.exists() && f.isDirectory()) {
                return sanitized;
            }
        }
        return defaultFhirPath;
    }
}
